name: Build and publish a 🛢️ container

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set variables
        run: |
          TAG=${{ github.ref_name }}
          echo "PUPPET_RELEASE=${TAG:0:1}" >> $GITHUB_ENV
          echo "PUPPETSERVER_VERSION=${TAG}" >> $GITHUB_ENV
      - name: Build Puppetserver ${{ env.PUPPETSERVER_VERSION }} container
        uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          build_args: |
            PUPPET_RELEASE=${{ env.PUPPET_RELEASE }}
            PUPPETSERVER_VERSION=${{ env.PUPPETSERVER_VERSION }}
          build_arch: linux/amd64 #,linux/arm64
          build_context: puppetserver
          buildfile: puppetserver/Dockerfile
